### PR TITLE
Add code to copy from location to destination and write to log file

### PR DESCRIPTION
**Pull request by Karlahaigh**

### CODE REVIEW

**Comment by Karlahaigh** [comment]
Hi guys,
learning curve on all fronts here. I added a line of code for the copy and append to a log. I'm not sure it is 100% correct but I feel like I am headed down the right path. Will you please take a look at it and let me know what you think?
Thank you!

**Comment by MsMadGirl** [comment]
I'm not seeing it as a commit, Karla. Are you sure you sent it to the
master branch? That's the most important part.

**Comment by Karlahaigh** [comment]
No, I did a separate branch cause I didn't want to screw anything up.
You'll have to look at the branches and look for karlas_attempt.

**Comment by MsMadGirl** [comment]
Aha. Thank you.

**Pull request merged**
